export const STATUS = {
    SUCCESS:"SUCCESS",
    FAIL:"FAIL",
    ERROR:"ERROR",
    NOT_FOUND:"NOT_FOUND",
    UNAUTHORIZED:"UNAUTHORIZED",
    INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR",
    BAD_REQUEST:"BAD_REQUEST",
    
}